### ISSUE TITLE
How to modify/adapt methods from API library?

### ISSUE THREAD

**Issue by drmanhadan** [bignerdranch/recyclerview-multiselect#11]
http://stackoverflow.com/questions/31645655/how-to-modify-adapt-methods-from-api-library

I'm using Big Nerd Ranch's recyclerview-multiselect library to give my RecyclerView's CardViews a multi-selection capability. I've worked out my app-specific kinks for the most part, but I ran into a pretty big issue. Whenever the RecyclerView is in SelectionMode and has to recreate a card (which is often, because that's practically the point of RecyclerView, at least if I understand it correctly,) it throws this error:

java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.support.v7.widget.RoundRectDrawableWithShadow
        at android.support.v7.widget.CardViewEclairMr1.getShadowBackground(CardViewEclairMr1.java:159)
        at android.support.v7.widget.CardViewEclairMr1.getMinWidth(CardViewEclairMr1.java:150)
        at android.support.v7.widget.CardView.onMeasure(CardView.java:181)
        at android.view.View.measure(View.java:16498)
Logically, I followed the error to whatever source was causing a StateListDrawable to be set as the CardView's background. What I found was summed up by a commented section in this class. It reads as follows:

selectionModeBackgroundDrawable defaults to a StateListDrawable that displays your colorAccent theme color when state_activated=true, and nothing otherwise.

In the SwappingHolder class, you can see where the StateListDrawable, causing the error, is being returned. Also, if you look in the CardViewEclairMr1.java, as suggested in the error, you can see the method that most directly causes the error:

private RoundRectDrawableWithShadow getShadowBackground(CardViewDelegate cardView) {
        return ((RoundRectDrawableWithShadow) cardView.getBackground());
    }
To be honest, after all this snooping around in the BigNerdRanch library, I'm still not sure what to do! I was thinking I might need to @Override the BigNerdRanch methodology which brings in a StateListDrawable, but that would be getting my hands so dirty with the library, it would defeat the purpose of implementing their API to begin with. How do I fix this error?

**Comment by drmanhadan** [comment]
To elaborate further, with the way SwappingHolder returns StateListDrawables, I cannot scroll ( in SelectionMode ) past a single card's view without the app crashing.

**Comment by jingibus** [comment]
There are a couple of options that could work in your situation.

1. Put your `CardView` inside another view. `SwappingHolder` relies on being able to swap out the background drawable for a view. `CardView` is managing its own background drawable, though, so the two tools start fighting with one another. If `CardView` is inside a plain `FrameLayout`, however, they won't have anything to fight over.
2. Instead of using `SwappingHolder`, roll your own by extending `MultiSelectorBindingHolder`. If you do this, you will have to implement visuals for selected views yourself, though.

**Comment by drmanhadan** [comment]
Love option number 1... great idea. I'll implement and let you know how it works in this thread.

**Comment by drmanhadan** [comment]
Okay, so the crashing is gone... but a new issue arrises that confuses me. I have the `CardViews` change their color to white whenever `SelectionMode` is toggled on. I do so by setting a `for() loop` to traverse my list of `mHolders` and setting the `RelativeLayout` background (contained within each `CardView`) to WHITE in `onCreateActionMode()`

     for (int go = 0; go < mHolders.size(); go++) {
                mHolders.get(go).vSubjectLayout.setBackgroundColor(Color.WHITE);
            }

However, whenever a `CardView` is brought out of the screen and back into the screen (by scrolling), the background changes back to whatever color it used to be.

**Comment by jingibus** [comment]
Call setBackgroundColor from within setSelected or setActivated on the holder instead. Make sure and call through to the superclass's implementation.

**Comment by drmanhadan** [comment]
Sorry, rookie Gitter here. Are you saying I need to override the `setSelected` or `setActivated` methods in the holder class with a `super()` call in each, or am I wayy off?

**Comment by jingibus** [comment]
Right. E.g.,

```
@Override
public void setSelected(boolean isSelected) {
    super.setSelected(isSelected);
    // do drmanhadan wizardry here
}
```

**Comment by drmanhadan** [comment]
This is where I was getting confused. When I did that (your simplified way and my way):

Your example mock-up:
       
         @Override
          public void setSelected(boolean isSelected) {
                 super.setSelected(isSelected);
                 // do drmanhadan wizardry here
          }

I get the error *"Cannot resolve method setSelected(boolean)"*

My way:

         @Override
         public void setSelected(boolean isSelected) {
             super.setSelected(isSelected);
             // do drmanhadan wizardry here
         }

I get the error *"SwappingHolder (android.view.View, com.bignerdranch.android.multiselector.MultiSelector in SwappingHolder cannot be applied to (com.bignerdranch.android.multiselector.SwappingHolder, boolean)"*

**Comment by jingibus** [comment]
Oop! I got the method names wrong. It's setSelectable, not setSelected.

Check the javadoc for `SelectableHolder` for more details on what setSelectable and setActivated do.

**Comment by drmanhadan** [comment]
I think I've got a good handle on where to go with this, but before I can move on I'm running into the same sort of issue.

*"android.view.View cannot be applied to boolean"* for implementation of `setSelected()`

**Comment by drmanhadan** [comment]
That doesn't seem to be able to keep them in the white color after they return to the screen.

          @Override
        public void setSelectable(boolean isSelectable) {
            super.setSelectable(isSelectable);
            //vSubjectLayout.setBackgroundColor(Color.WHITE);
        }
        @Override
        public void setActivated(boolean isActivated) {
            super.setActivated(isActivated);
            vSubjectLayout.setBackgroundColor(Color.WHITE);
        }
        public void bindCrime(SubjectInfo si) {
            sInfo = si;
            vSubjectName.setText(sInfo.subjectName);
            vSubjectGrade.setText(Integer.toString(si.subjectGrade));
            vSubjectLayout.setBackgroundColor(
                    Color.parseColor(SubjectAdapter.giveSubjectHexValue((double) si.subjectGrade)));
        }

Tried both, but no cigar. They return to the color likely because in the `bindCrime()` is what tells it to. So, how do I get bindCrime to only bind when not in selection mode?

**Comment by jingibus** [comment]
Check the value of isSelected() and isActivated() inside bindCrime, and set the background color accordingly.

**Comment by drmanhadan** [comment]
I couldn't get the `if(!isActivated || !isSelectable)` statement to go through, but I've got everything working great now! ...for the time being. I'll post my solution

        @Override
        public void setSelectable(boolean isSelectable) {
            super.setSelectable(isSelectable);
        }

        @Override
        public void setActivated(boolean isActivated) {
            super.setActivated(isActivated);
            vSubjectLayout.setBackgroundColor(Color.WHITE);
        }

        public void bindCrime(SubjectInfo si) {
            sInfo = si;
            vSubjectName.setText(sInfo.subjectName);
            vSubjectGrade.setText(Integer.toString(si.subjectGrade));
            if (mMultiSelector.getSelectedPositions().size()==0) {
                vSubjectLayout.setBackgroundColor(
                        Color.parseColor(SubjectAdapter.giveSubjectHexValue((double) si.subjectGrade)));
            }
        }

and in the creation of my `mEditOrDeleteMode`

        @Override
        public void onDestroyActionMode(ActionMode actionMode) {
            super.onDestroyActionMode(actionMode);
            cAdapter.notifyDataSetChanged();
        }

above code is just to get the colors to return. I have code elsewhere that checks when nothing is selected and toggled `SelectionMode` to off.

**A huge thanks** for all your direction and help. Glad to know a 'librarian' who cares about his fellow Gitters. Hopefully, you won't hear from me soon!
