### ISSUE TITLE
ClassCastException is raised when trying to scroll while actionmode is created.

### ISSUE THREAD

**Issue by Protino** [bignerdranch/recyclerview-multiselect#14]
Trace:
1.Long clicked on an item.
2. When I start scrolling the app crashes and below is some part of the crash report.

<code> java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast
 to android.support.v7.widget.RoundRectDrawableWithShadow 
at android.support.v7.widget.CardViewEclairMr1.getShadowBackground(CardViewEclairMr1.java:159)
            at android.support.v7.widget.CardViewEclairMr1.getMinWidth(CardViewEclairMr1.java:150)
            at android.support.v7.widget.CardView.onMeasure(CardView.java:181)
            at android.view.View.measure(View.java:16514)
            at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:6635)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1385)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1322)
            at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1150)
            at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1007)
            at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1355)
            at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2209)
            at android.view.View.dispatchTouchEvent(View.java:7706)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2214)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2220)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2220)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2220)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2220)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
</code>

NOTE : I'm using cardview (from android support library itself) as list item of the recycler view.

UPDATE: It doesn't occur frequently on devices running 4.1.2 or on 5.0. It does occur each and  every time on my Lenovo a6000 which has 4.4.4.

**Comment by jingibus** [comment]
`SwappingHolder` works by swapping out the drawables of the top-level `View`. `CardView` uses its own drawables, so it will not work if you use it as the top-level `View`.

I do not know of a way to fix `SwappingHolder` to handle this, but you can fix it by wrapping the `CardView` in a `FrameLayout`.

**Comment by Protino** [comment]
How do i wrap <code>CardView</code> inside a <code>FrameLayout</code> and doesn't <code>CardView</code> extend <code>FrameLayout</code> ? Why wrap it again?

**Comment by jingibus** [comment]
Make it a child of a `FrameLayout`, that's all I mean:

```
<FrameLayout
    ...
    >
    <CardView 
        ...
        >
    </CardView>
</FrameLayout>
```

The problem is that `CardView` uses its own background. `SwappingHolder` needs to be able to replace that background to do its work.

Another option would be to implement the `SelectableHolder` interface yourself, and choose how you want to display a selected item.

**Comment by Protino** [comment]
Thanks a lot man, but the listeners are not working now. I tried setting listeners on to the <code>CardView</code> directly , it works fine only for single selection.
